// booking-angular/src/app/components/rentals/rental-details/rental-details.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-rentals-details',
  templateUrl: './rental-details.component.html',
  styleUrls: ['./rental-details.component.scss']
})
export class RentalDetailsComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<section id="rentalDetails">
  <div class="upper-section">
    <div class="row">
      <div class="col-md-6">
        <img
          src="{{rental?.image}}"
          alt="{{rental?.description}}"
          class="img-fluid"
        >
      </div>
      <div class="col-md-6">
        <!--
          we are passing to the child component data that will be stored in
          location member variable in TomtomComponent
        -->
        <app-tomtom
          [location] = "rentalLocation"></app-tomtom>
      </div>
    </div>
  </div>

  <div class="details-section">
    <div class="row">
      <div class="col-md-8">
        <div class="rental">
          <h2 class="rental-type type-{{rental?.category}}">
            {{ (rental?.shared ? "Shared" : "Whole")  | upper}}
            {{ rental?.category | upper }}
          </h2>
          <h1 [appHighlight]="'ivory'" class="rental-title">
            {{ rental?.title }}
          </h1>
          <h2 class="rental-city">
          <!-- same as using second pipe            -->
            {{ rental?.city | upper:'firstUpperLetter' }}
          </h2>
          <div class="rental-room-info">
            <span>
              <i class="fa fa-building"></i>
              {{ rental?.numOfRooms }} bedrooms
            </span>
            <span>
              <i class="fa fa-user"></i>
              {{ rental?.numOfRooms + 4 }} guests
            </span>
            <span>
              <i class="fa fa-bed"></i>
              {{ rental?.numOfRooms + 2 }} beds
            </span>
          </div>
          <p class="rental-description">
            {{rental?.description}}
          </p>
          <hr>
          <div class="rental-assets" [appHighlight]="'lightyellow'">
            <h3 class="title">Assets</h3>
            <div class="row">
              <div class="col-md-6">
                <span>
                  <i class="fa fa-asterisk"></i> Cooling
                </span>
                <span>
                  <i class="fa fa-thermometer"></i> Heating
                </span>
                <span>
                  <i class="fa fa-location-arrow"></i> Iron
                </span>
              </div>
              <div class="col-md-6">
                <span>
                  <i class="fa fa-desktop"></i> Working area
                </span>
                <span>
                  <i class="fa fa-cube"></i> Washing machine
                </span>
                <span>
                  <i class="fa fa-cube"></i> Dishwasher
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <app-rental-booking
          [rental]="rental"
          [isAuth]="auth.isAuthenticated">
        </app-rental-booking>
      </div>
    </div>
  </div>
</section>

// booking-react/src/components/pages/rentaldetails-component/RentalDetails.js
import React from 'react'

class RentalDetails extends React.Component {
    render() {
        return (
            <section id="rentalDetails">
                <div className="upper-section">
                    <div className="row">
                        <div className="col-md-6">
                            {/* <!-- TODO: Display rental image --> */}
                            <img src="#" alt=""/>
                        </div>
                        <div className="col-md-6">
                            {/* <!-- TODO: Display rental image --> */}
                            <img src="#" alt=""/>
                        </div>
                    </div>
                </div>

                <div className="details-section">
                    <div className="row">
                        <div className="col-md-8">
                            <div className="rental">
                                {/* <!-- TODO: Display shared category --> */}
                                <h2 className="rental-type">true house</h2>
                                {/* <!-- TODO: Display title --> */}
                                <h1 className="rental-title">Some Title</h1>
                                {/* <!-- TODO: Display city --> */}
                                <h2 className="rental-city">New York</h2>
                                <div className="rental-room-info">
                                    {/* <!-- TODO: Display numOfRooms --> */}
                                    <span><i className="fa fa-building"></i>4 bedrooms</span>
                                    {/* // <!-- TODO: Display numOfRooms + 4 --> */}
                                    <span><i className="fa fa-user"></i> 8 guests</span>
                                    {/* // <!-- TODO: Display numOfRooms + 2 --> */}
                                    <span><i className="fa fa-bed"></i> 6 beds</span>
                                </div>
                                {/* <!-- TODO: Display description --> */}
                                <p className="rental-description">
                                    Some Description
                                </p>
                                <hr/>
                                <div className="rental-assets">
                                    <h3 className="title">Assets</h3>
                                    <div className="row">
                                        <div className="col-md-6">
                                            <span><i className="fa fa-asterisk"></i> Cooling</span>
                                            <span><i className="fa fa-thermometer"></i> Heating</span>
                                            <span><i className="fa fa-location-arrow"></i> Iron</span>
                                        </div>
                                        <div className="col-md-6">
                                            <span><i className="fa fa-desktop"></i> Working area</span>
                                            <span><i className="fa fa-cube"></i> Washing machine</span>
                                            <span><i className="fa fa-cube"></i> Dishwasher</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-4"> BOOKING</div>
                    </div>
                </div>
            </section>
        )
    }
}

export default RentalDetails;
