// booking-angular/src/app/components/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import {AbstractControl, FormBuilder, FormGroup, Validators} from "@angular/forms";
import {forbiddenEmailValidator, sameAsValidator } from "../../../validators/functions";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  loginForm: FormGroup
  emailPattern = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/

  constructor(private fb: FormBuilder) { }

  ngOnInit(): void {
    this.initForm();
  }

  initForm(): void {
    this.loginForm = this.fb.group({
        email: [
          '',
          [
            Validators.required,
            Validators.pattern(this.emailPattern),
            forbiddenEmailValidator('david.vera@8online.fr')
          ]
        ],
        password: [
          '',
          [
            Validators.required,
            Validators.minLength(6)
          ]
        ]
    });
  }

  // initForm(): void {
  //   this.loginForm = this.fb.group({
  //     email: [
  //       '',
  //       [
  //         Validators.required,
  //         Validators.pattern(this.emailPattern),
  //         forbiddenEmailValidator('david.vera@8online.fr')
  //       ]
  //     ],
  //     password: [
  //       '',
  //       [
  //         Validators.required,
  //         Validators.minLength(6)
  //       ]
  //     ]},
  //     {validators: [sameAsValidator(['password', 'email'])]}
  //     );
  // }

  get email(): AbstractControl  {
    return this.loginForm.get('email');
  }
  get password():AbstractControl  {
    return this.loginForm.get('password');
  }

  login() {
    if (this.loginForm.invalid)
      return;
    alert(this.formDiagnostic)
  }

  get formDiagnostic(): string {
    return JSON.stringify(this.loginForm.value)
  }
}

<section id="login">
  <div class="booking-form">
    <div class="row">
      <div class="col-md-5">
        <h1>Login</h1>
        <!-- <div *ngIf="notifyMessage" class="alert alert-success">
          Some message
        </div> -->
        <!-- reactive form -->
        <form [formGroup]="loginForm">
          <div class="form-group">
            <label for="email">Email</label>
            <input
              formControlName="email"
              type="email"
              class="form-control"
              id="email">
          </div>
          <div
            class="alert alert-danger"
            *ngIf="email.invalid && !email.pristine"
            >
            <div *ngIf="email.errors.required">
              Email is required
            </div>
            <div *ngIf="email.errors.pattern">
              Must be valid email format
            </div>
            <div *ngIf="email.errors.forbiddenEmail">
              This email is not allowed!
            </div>

          </div>

          <div class="form-group">
            <label for="password">Password</label>
            <input
              formControlName="password"
              type="password"
              class="form-control"
              id="password">
          </div>
          <div
            class="alert alert-danger"
            *ngIf="password.invalid && !password.pristine"
          >
            <div *ngIf="password.errors.required">
              Password is required
            </div>
            <div *ngIf="password.errors.minlength">
              Minimum length of password is 6 characters
            </div>
          </div>
          <!-- <div
            *ngIf="loginForm.errors?.sameAs && !password.pristine"
            class="alert alert-danger">
            Password  must be the same as email!
          </div> -->

          <button
            (click)="login()"
            [disabled]="loginForm.invalid"
            type="submit"
            class="btn btn-outline-success my-2 my-sm-0 booking-btn-main">
            Submit
          </button>
        </form>

        <div>
          {{formDiagnostic}}
        </div>

        <!-- <div *ngIf="errors.length > 0" class="alert alert-danger">
          <p *ngFor="let error of errors">
            {{error.detail}}
          </p>
        </div> -->
      </div>
      <div class="col-md-6 ml-auto">
        <div class="image-container">
          <h2 class="catchphrase">Hundreds of awesome places in reach of few clicks.</h2>
          <img src="assets/images/login-image.jpg" alt="">
        </div>
      </div>
    </div>
  </div>
</section>

// booking-react/src/components/pages/auth-component/Login.js
import React from 'react';

class Login extends React.Component {
    render() {
        return(
            <div className="booking-form">
                <div className="row">
                    <div className="col-md-5">
                        <h1 className="page-title">Login</h1>
                        {/* <!-- <div className="alert alert-success">
        Some message
      </div> --> */}
                        <form>
                            <div className="form-group">
                                <label htmlFor="email">Email</label>
                                <input
                                    type="email"
                                    className="form-control"
                                    id="email" />
                                {/* <div className="alert alert-danger">
            <div>
              Email is required.
            </div>
            <div>
              Must be valid email format!
            </div>
          </div> */}
                            </div>
                            <div className="form-group">
                                <label htmlFor="password">Password</label>
                                <input
                                    type="password"
                                    className="form-control"
                                    id="password" />
                            </div>
                            <button
                                type="submit"
                                className="btn btn-bwm-main">Submit</button>
                        </form>
                        {/* <div className="alert alert-danger">
        <p>
          Some Error
        </p>
      </div> --> */}
                    </div>
                    <div className="col-md-6 ml-auto">
                        <div className="image-container">
                            <h2 className="catchphrase">Hundreds of awesome places in reach of few clicks.</h2>
                            <img src="/images/login-image.jpg" alt="Login an user" />
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}

export default Login;
