// booking-react/src/components/pages/auth-component/Register.js
import React from 'react';

class Register extends React.Component {
    render() {
        return(
            <div className="booking-form">
                <div className="row">
                    <div className="col-md-5">
                        <h1 className="page-title">Register</h1>
                        <form>
                            <div className="form-group">
                                <label htmlFor="username">Username</label>
                                <input
                                    type="text"
                                    className="form-control"
                                    id="username" />
                                {/* <div className="alert alert-danger">
            <div *ngIf="username.errors.required">
              Username is required.
            </div>
          </div> */}
                            </div>

                            <div className="form-group">
                                <label htmlFor="email">Email</label>
                                <input
                                    type="email"
                                    className="form-control"
                                    id="email" />
                            </div>

                            <div className="form-group">
                                <label htmlFor="password">Password</label>
                                <input
                                    type="password"
                                    className="form-control"
                                    id="password" />
                            </div>

                            <div className="form-group">
                                <label htmlFor="passwordConfirmation">Confirm Password</label>
                                <input
                                    type="password"
                                    className="form-control"
                                    id="passwordConfirmation" />
                            </div>
                            <button
                                type="submit"
                                className="btn btn-booking-main">Submit</button>
                        </form>
                        {/* <div className="alert alert-danger">
        <p>
          Some Error
        </p>
      </div> */}
                    </div>
                    <div className="col-md-6 ml-auto">
                        <div className="image-container">
                            <h2 className="catchphrase">As our member you have access to most awesome places in the world.</h2>
                            <img src="/images/register-image.jpg" alt="Register an user" />
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}

export default Register;

// booking-angular/src/app/components/auth/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import {RegisterForm} from "../../../shared/registerForm.model";
import {NgForm} from "@angular/forms";

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {
  registerFormData: RegisterForm;
  emailPattern = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/


  constructor() {
    this.registerFormData =  new RegisterForm();
  }

  ngOnInit(): void {
  }

  register(form: NgForm): void {
    // alert(JSON.stringify(this.registerFormData));
    if (form.invalid) {
      return;
    }
  }
  validateInputs(form: NgForm): void {
    Object.keys(form.controls).forEach(controlName => {
      form.controls[controlName].markAsDirty();
    });
  }

  diagnostic(): string {
    return JSON.stringify(this.registerFormData)
  }

  get formDiagnostic(): string {
    return JSON.stringify(this.registerFormData)
  }
}

<section id="register">
  <div class="booking-form">
    <div class="row">
      <div class="col-md-5">
        <h1 class="page-title">Register</h1>
        <!-- template driven form -->
        <form #registrationForm = "ngForm">
          <div class="form-group">
            <label for="username">Username</label>
            <input
              [(ngModel)]="registerFormData.username"
              name="username"
              required
              #username = "ngModel"
              minlength="4"
              type="text"
              class="form-control"
              id="username"
            >
          </div>
          <div *ngIf="username.invalid && username.pristine === false" class="alert alert-danger">
            <div *ngIf="username.errors.required">
              Username is required.
            </div>
            <div *ngIf="username.errors.minlength">
              Username must be at least 4 characters long!
            </div>
          </div>


          <div class="form-group">
            <label for="email">Email</label>
            <input
              [(ngModel)]="registerFormData.email"
              name="email"
              required
              #email = "ngModel"
              [pattern]="emailPattern"
              type="email"
              class="form-control"
              id="email">
          </div>
          <div *ngIf="email.invalid && email.pristine === false" class="alert alert-danger">
            <div *ngIf="email.errors.required">
              Email is required!
            </div>
            <div *ngIf="email.errors.pattern">
              Email format is not valid!
            </div>
          </div>


          <div class="form-group">
            <label for="password">Password</label>
            <input
              [(ngModel)]="registerFormData.password"
              name="password"
              required
              #password = "ngModel"
              minlength="6"
              type="password"
              class="form-control"
              id="password">
          </div>
          <div *ngIf="password.invalid && password.pristine === false" class="alert alert-danger">
            <div *ngIf="password.errors.required">
              Password is required!
            </div>
            <div *ngIf="password.errors.minlength">
              Password must be at least 6 characters long!
            </div>
          </div>

          <div class="form-group">
            <label for="passwordConfirmation">Confirm Password</label>
            <input
              [(ngModel)]="registerFormData.passwordConfirmation"
              name="passwordConfirmation"
              type="password"
              required
              #passwordConfirmation = "ngModel"
              minlength="6"
              class="form-control"
              id="passwordConfirmation">
          </div>
          <div
            *ngIf="passwordConfirmation.invalid && passwordConfirmation.pristine === false"
            class="alert alert-danger">
            <div *ngIf="passwordConfirmation.errors.required">
              Password Confirmation is required!
            </div>
            <div *ngIf="passwordConfirmation.errors.minlength">
              Password Confirmation must be at least 6 characters long!
            </div>
          </div>

          <button
            [disabled] = "registrationForm.invalid"
            (click) = "register(registrationForm)"
            type="submit"
            class="btn btn-outline-success my-2 my-sm-0 booking-btn-main">
            Submit
          </button>
        </form>
        <!-- <div>
          {{ diagnostic() }} <br />
          {{formDiagnostic}}
        </div> -->
        <!-- <div class="alert alert-danger">
          <p *ngFor="let error of errors">
            {{error.detail}}
          </p>
        </div> -->
      </div>
      <div class="col-md-6 ml-auto">
        <div class="image-container">
          <h2 class="catchphrase">As our member you have access to most awesome places in the world.</h2>
          <img src="assets/images/register-image.jpg" alt="">
        </div>
      </div>
    </div>
  </div>
</section>
